export {default as Navbar} from "./Navbar/Navbar"
export {default as Header} from "./Header/Header"
export {default as TopOffers} from "./TopOffers/TopOffers"
export {default as PropertyCard} from "./PropertyCard/PropertyCard"
export {default as AboutUs} from "./About/About"
export {default as OurTeam} from "./Team/OurTeam"